### ISSUE TITLE
tests for visualization

### ISSUE THREAD

**Issue by brandondube** [IBM/complex-linear-network-analyzer#14]
From the JOSS thread -- there are some breaks to the visualization code if it is used without setup, being addressed in #13.  I may recommend "functional" testing, even if not correctness testing, for plotting.  If you produce matplotlib figures, you can just run the plotting code, return the figure and/or axis, and assert them.  This ensures there are no syntax or other preliminary errors, but does not assure correctness.  For things that use graphviz, etc, you may just want to assert that the exit code from graphviz was 0.

**Comment by pstrk** [comment]
I created a set of tests for the visualization features (#17). They indeed just check that output is generated/the functions return the expected value, but correctness of the visualization is not checked.
